### PR TITLE
Fix 'RESET to this week' when week begins Monday

### LINKED ISSUE #55: 'RESET to this week' when week begins Monday is off by one
Given:
- the current day is a Sunday
- the user has set the range mode to 'Week'
- the user has set the 'Week starts on' option to 'Monday'

When
- the user clicks 'RESET to this week'

Then
- expected behaviour: the range is set to the current week
- actual behaviour: the range is set to the next week

Example: set your system clock to 2019-11-10, go to week mode and set 'Week starts on' to 'Monday', then click 'RESET to this week' - it'll set the range as `11.11.2019 - 18.11.2019`, despite the current date (`10.11.2019`) not being in that range.

### PR DESCRIPTION
**Pull request by domdomegg**
Fixes #55

### CODE REVIEW

**Comment by aronwoost** [comment]
@domdomegg Can you fix conflict pls?

Thanks for tackling that issue! 🔥

**Comment by domdomegg** [comment]
Fixed 🎉

Thanks for the review!

**Comment by aronwoost** [comment]
I tested it and it works! 👍🚀

Thanks for providing the fix and sorry for the loooooong delay. 😬😇

**Comment by domdomegg** [comment]
No problem, thanks for reviewing and testing it! No worries about the delay 😄

**Pull request merged**
